# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class demoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.hellojlc = channel.unary_unary(
                '/test.demo/hellojlc',
                request_serializer=test__pb2.hellojlcReq.SerializeToString,
                response_deserializer=test__pb2.hellojlcReply.FromString,
                )
        self.TestClientRecvStream = channel.unary_stream(
                '/test.demo/TestClientRecvStream',
                request_serializer=test__pb2.TestClientRecvStreamRequest.SerializeToString,
                response_deserializer=test__pb2.TestClientRecvStreamResponse.FromString,
                )
        self.TestClientSendStream = channel.stream_unary(
                '/test.demo/TestClientSendStream',
                request_serializer=test__pb2.TestClientSendStreamRequest.SerializeToString,
                response_deserializer=test__pb2.TestClientSendStreamResponse.FromString,
                )
        self.TestTwoWayStream = channel.stream_stream(
                '/test.demo/TestTwoWayStream',
                request_serializer=test__pb2.TestTwoWayStreamRequest.SerializeToString,
                response_deserializer=test__pb2.TestTwoWayStreamResponse.FromString,
                )


class demoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def hellojlc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestClientRecvStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestClientSendStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestTwoWayStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_demoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'hellojlc': grpc.unary_unary_rpc_method_handler(
                    servicer.hellojlc,
                    request_deserializer=test__pb2.hellojlcReq.FromString,
                    response_serializer=test__pb2.hellojlcReply.SerializeToString,
            ),
            'TestClientRecvStream': grpc.unary_stream_rpc_method_handler(
                    servicer.TestClientRecvStream,
                    request_deserializer=test__pb2.TestClientRecvStreamRequest.FromString,
                    response_serializer=test__pb2.TestClientRecvStreamResponse.SerializeToString,
            ),
            'TestClientSendStream': grpc.stream_unary_rpc_method_handler(
                    servicer.TestClientSendStream,
                    request_deserializer=test__pb2.TestClientSendStreamRequest.FromString,
                    response_serializer=test__pb2.TestClientSendStreamResponse.SerializeToString,
            ),
            'TestTwoWayStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TestTwoWayStream,
                    request_deserializer=test__pb2.TestTwoWayStreamRequest.FromString,
                    response_serializer=test__pb2.TestTwoWayStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.demo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class demo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def hellojlc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.demo/hellojlc',
            test__pb2.hellojlcReq.SerializeToString,
            test__pb2.hellojlcReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestClientRecvStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/test.demo/TestClientRecvStream',
            test__pb2.TestClientRecvStreamRequest.SerializeToString,
            test__pb2.TestClientRecvStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestClientSendStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/test.demo/TestClientSendStream',
            test__pb2.TestClientSendStreamRequest.SerializeToString,
            test__pb2.TestClientSendStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestTwoWayStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/test.demo/TestTwoWayStream',
            test__pb2.TestTwoWayStreamRequest.SerializeToString,
            test__pb2.TestTwoWayStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
