# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"(\n\x0bhellojlcReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x1f\n\rhellojlcReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"+\n\x1bTestClientRecvStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientRecvStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"+\n\x1bTestClientSendStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientSendStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\'\n\x17TestTwoWayStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"*\n\x18TestTwoWayStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xdb\x02\n\x04\x64\x65mo\x12\x34\n\x08hellojlc\x12\x11.test.hellojlcReq\x1a\x13.test.hellojlcReply\"\x00\x12\x61\n\x14TestClientRecvStream\x12!.test.TestClientRecvStreamRequest\x1a\".test.TestClientRecvStreamResponse\"\x00\x30\x01\x12\x61\n\x14TestClientSendStream\x12!.test.TestClientSendStreamRequest\x1a\".test.TestClientSendStreamResponse\"\x00(\x01\x12W\n\x10TestTwoWayStream\x12\x1d.test.TestTwoWayStreamRequest\x1a\x1e.test.TestTwoWayStreamResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOJLCREQ']._serialized_start=20
  _globals['_HELLOJLCREQ']._serialized_end=60
  _globals['_HELLOJLCREPLY']._serialized_start=62
  _globals['_HELLOJLCREPLY']._serialized_end=93
  _globals['_TESTCLIENTRECVSTREAMREQUEST']._serialized_start=95
  _globals['_TESTCLIENTRECVSTREAMREQUEST']._serialized_end=138
  _globals['_TESTCLIENTRECVSTREAMRESPONSE']._serialized_start=140
  _globals['_TESTCLIENTRECVSTREAMRESPONSE']._serialized_end=186
  _globals['_TESTCLIENTSENDSTREAMREQUEST']._serialized_start=188
  _globals['_TESTCLIENTSENDSTREAMREQUEST']._serialized_end=231
  _globals['_TESTCLIENTSENDSTREAMRESPONSE']._serialized_start=233
  _globals['_TESTCLIENTSENDSTREAMRESPONSE']._serialized_end=279
  _globals['_TESTTWOWAYSTREAMREQUEST']._serialized_start=281
  _globals['_TESTTWOWAYSTREAMREQUEST']._serialized_end=320
  _globals['_TESTTWOWAYSTREAMRESPONSE']._serialized_start=322
  _globals['_TESTTWOWAYSTREAMRESPONSE']._serialized_end=364
  _globals['_DEMO']._serialized_start=367
  _globals['_DEMO']._serialized_end=714
# @@protoc_insertion_point(module_scope)
